/*
 * Generated by scripts/generate-api-types.js.
 * Sources: lib/api-catalog.js, lib/types.js, docs/api-responses-reference.json.
 * Do not edit this file directly.
 */
import type {
  AdGuardHomeGetConfig,
  AddPortForwardParams,
  AddStaticBindParams,
  AddTunnelParams,
  ClientsGetStatus,
  CloudGetConfig,
  DdnsGetConfig,
  DdnsGetStatus,
  DnsGetConfig,
  FanGetConfig,
  FanGetStatus,
  LanSetConfigParams,
  LedGetConfig,
  LocalAccessSetConfigParams,
  OvpnServerSetConfigParams,
  PluginsInstallParams,
  RepeaterConnectParams,
  RepeaterGetConfig,
  RepeaterGetStatus,
  SetDmzParams,
  SetDnsConfigParams,
  SetPasswordParams,
  SetSpeedLimitRuleParams,
  SetTunnelParams,
  SetWanAccessParams,
  SetWifiConfigParams,
  SystemGetInfo,
  SystemGetStatus,
  TailscaleGetConfig,
  TailscaleGetStatus,
  TailscaleSetConfigParams,
  TimerSetParams,
  TorGetConfig,
  UpgradeGetConfig,
  VpnOptionsParams,
  WgClientAddConfigParams,
  WgServerAddPeerParams,
  WgServerSetConfigParams,
  WifiGetStatus,
} from './lib/types';

export type {
  AdGuardHomeGetConfig,
  AddPortForwardParams,
  AddStaticBindParams,
  AddTunnelParams,
  ClientsGetStatus,
  CloudGetConfig,
  DdnsGetConfig,
  DdnsGetStatus,
  DnsGetConfig,
  FanGetConfig,
  FanGetStatus,
  LanSetConfigParams,
  LedGetConfig,
  LocalAccessSetConfigParams,
  OvpnServerSetConfigParams,
  PluginsInstallParams,
  RepeaterConnectParams,
  RepeaterGetConfig,
  RepeaterGetStatus,
  SetDmzParams,
  SetDnsConfigParams,
  SetPasswordParams,
  SetSpeedLimitRuleParams,
  SetTunnelParams,
  SetWanAccessParams,
  SetWifiConfigParams,
  SystemGetInfo,
  SystemGetStatus,
  TailscaleGetConfig,
  TailscaleGetStatus,
  TailscaleSetConfigParams,
  TimerSetParams,
  TorGetConfig,
  UpgradeGetConfig,
  VpnOptionsParams,
  WgClientAddConfigParams,
  WgServerAddPeerParams,
  WgServerSetConfigParams,
  WifiGetStatus,
} from './lib/types';

export type RpcParams = Record<string, unknown>;

/** Object keys observed for system.get_load on firmware 4.8.1. */
export interface SystemGetLoadObservedResponse {
  "memory_free"?: unknown;
  "memory_buff_cache"?: unknown;
  "memory_total"?: unknown;
  "load_average"?: unknown;
}

/** Object keys observed for system.get_timezone_config on firmware 4.8.1. */
export interface SystemGetTimezoneConfigObservedResponse {
  "zonename"?: unknown;
  "tzoffset"?: unknown;
  "autotimezone_enabled"?: unknown;
  "localtime"?: unknown;
  "timestamp"?: unknown;
  "timezone"?: unknown;
}

/** Object keys observed for system.get_usb3_disable on firmware 4.8.1. */
export interface SystemGetUsb3DisableObservedResponse {
  "usb3_disable"?: unknown;
}

/** Object keys observed for vpn-client.get_status on firmware 4.8.1. */
export interface VpnClientGetStatusObservedResponse {
  "status_list"?: unknown;
  "mode"?: unknown;
}

/** Object keys observed for vpn-client.get_all_config_list on firmware 4.8.1. */
export interface VpnClientGetAllConfigListObservedResponse {
  "configs"?: unknown;
}

/** Object keys observed for vpn-client.get_tunnel on firmware 4.8.1. */
export interface VpnClientGetTunnelObservedResponse {
  "default_tunnels"?: unknown;
  "tunnels"?: unknown;
  "global_enabled"?: unknown;
}

/** Object keys observed for vpn-client.get_connection_methods on firmware 4.8.1. */
export interface VpnClientGetConnectionMethodsObservedResponse {
  "connection_methods"?: unknown;
}

/** Object keys observed for wg-client.get_group_list on firmware 4.8.1. */
export interface WgClientGetGroupListObservedResponse {
  "groups"?: unknown;
}

/** Object keys observed for wg-server.get_config on firmware 4.8.1. */
export interface WgServerGetConfigObservedResponse {
  "port"?: unknown;
  "address_v6"?: unknown;
  "initialization"?: unknown;
  "private_key"?: unknown;
  "public_key"?: unknown;
  "local_access"?: unknown;
  "address_v4"?: unknown;
}

/** Object keys observed for wg-server.get_setting on firmware 4.8.1. */
export interface WgServerGetSettingObservedResponse {
  "client_to_client"?: unknown;
  "masq"?: unknown;
  "local_access"?: unknown;
}

/** Object keys observed for wg-server.get_peer_list on firmware 4.8.1. */
export interface WgServerGetPeerListObservedResponse {
  "peers"?: unknown;
}

/** Object keys observed for ovpn-client.get_group_list on firmware 4.8.1. */
export interface OvpnClientGetGroupListObservedResponse {
  "groups"?: unknown;
}

/** Object keys observed for ovpn-server.get_config on firmware 4.8.1. */
export interface OvpnServerGetConfigObservedResponse {
  "dh"?: unknown;
  "lzo"?: unknown;
  "port"?: unknown;
  "end"?: unknown;
  "subnetv6"?: unknown;
  "mode"?: unknown;
  "local_access"?: unknown;
  "proto"?: unknown;
  "tap_address"?: unknown;
  "subnetv4"?: unknown;
  "tap_mask"?: unknown;
  "access_scope"?: unknown;
  "cipher"?: unknown;
  "initialization"?: unknown;
  "client_auth"?: unknown;
  "mask"?: unknown;
  "verb"?: unknown;
  "start"?: unknown;
  "hmac"?: unknown;
  "client_to_client"?: unknown;
  "auth"?: unknown;
}

/** Object keys observed for ovpn-server.get_setting on firmware 4.8.1. */
export interface OvpnServerGetSettingObservedResponse {
  "local_access"?: unknown;
  "masq"?: unknown;
}

/** Object keys observed for ovpn-server.get_user_list on firmware 4.8.1. */
export interface OvpnServerGetUserListObservedResponse {
  "user_list"?: unknown;
}

/** Object keys observed for wifi.get_config on firmware 4.8.1. */
export interface WifiGetConfigObservedResponse {
  "res"?: unknown;
  "dfs_support"?: unknown;
}

/** Object keys observed for clients.get_list on firmware 4.8.1. */
export interface ClientsGetListObservedResponse {
  "clients"?: unknown;
}

/** Object keys observed for firewall.get_port_forward_list on firmware 4.8.1. */
export interface FirewallGetPortForwardListObservedResponse {
  "res"?: unknown;
}

/** Object keys observed for firewall.get_rule_list on firmware 4.8.1. */
export interface FirewallGetRuleListObservedResponse {
  "res"?: unknown;
}

/** Object keys observed for firewall.get_zone_list on firmware 4.8.1. */
export interface FirewallGetZoneListObservedResponse {
  "internals"?: unknown;
  "externals"?: unknown;
}

/** Object keys observed for firewall.get_dmz on firmware 4.8.1. */
export interface FirewallGetDmzObservedResponse {
  "enabled"?: unknown;
}

/** Object keys observed for firewall.get_wan_access on firmware 4.8.1. */
export interface FirewallGetWanAccessObservedResponse {
  "enable_https"?: unknown;
  "enable_ping"?: unknown;
  "enable_ssh"?: unknown;
  "whitelist"?: unknown;
  "enable_whitelist"?: unknown;
}

/** Object keys observed for dns.get_info on firmware 4.8.1. */
export interface DnsGetInfoObservedResponse {
  "protos"?: unknown;
  "serverlist"?: unknown;
  "dnscrypt_version"?: unknown;
}

/** Object keys observed for lan.get_config_list on firmware 4.8.1. */
export interface LanGetConfigListObservedResponse {
  "interfaces"?: unknown;
}

/** Object keys observed for lan.get_static_bind_list on firmware 4.8.1. */
export interface LanGetStaticBindListObservedResponse {
  "static_bind_list"?: unknown;
}

/** Object keys observed for lan.get_wan_info on firmware 4.8.1. */
export interface LanGetWanInfoObservedResponse {
  "wan_info"?: unknown;
}

/** Object keys observed for network.get_advance_config on firmware 4.8.1. */
export interface NetworkGetAdvanceConfigObservedResponse {
  "nat_enable"?: unknown;
  "sip_enable"?: unknown;
}

/** Object keys observed for network.get_netnat_config on firmware 4.8.1. */
export interface NetworkGetNetnatConfigObservedResponse {
  "list"?: unknown;
  "enable"?: unknown;
  "qos_enabled"?: unknown;
  "actype"?: unknown;
  "wifi_reload"?: unknown;
}

/** Object keys observed for network.get_arp_list on firmware 4.8.1. */
export interface NetworkGetArpListObservedResponse {
  "entries"?: unknown;
}

/** Object keys observed for cable.get_config on firmware 4.8.1. */
export interface CableGetConfigObservedResponse {
  "protocol"?: unknown;
}

/** Object keys observed for cable.get_ports_config on firmware 4.8.1. */
export interface CableGetPortsConfigObservedResponse {
  "ports"?: unknown;
}

/** Object keys observed for cable.get_ports_status on firmware 4.8.1. */
export interface CableGetPortsStatusObservedResponse {
  "ports"?: unknown;
}

/** Object keys observed for repeater.get_saved_ap_list on firmware 4.8.1. */
export interface RepeaterGetSavedApListObservedResponse {
  "res"?: unknown;
}

/** Object keys observed for tethering.get_status on firmware 4.8.1. */
export interface TetheringGetStatusObservedResponse {
  "status"?: unknown;
  "devices"?: unknown;
}

/** Object keys observed for netmode.get_mode on firmware 4.8.1. */
export interface NetmodeGetModeObservedResponse {
  "mode"?: unknown;
}

/** Object keys observed for timer.get_led on firmware 4.8.1. */
export interface TimerGetLedObservedResponse {
  "turnon_hour"?: unknown;
  "turnoff_min"?: unknown;
  "turnon_min"?: unknown;
  "enable"?: unknown;
  "week"?: unknown;
  "turnoff_hour"?: unknown;
}

/** Object keys observed for timer.get_reboot on firmware 4.8.1. */
export interface TimerGetRebootObservedResponse {
  "enable"?: unknown;
  "week"?: unknown;
  "hour"?: unknown;
  "min"?: unknown;
}

/** Object keys observed for timer.get_wifi on firmware 4.8.1. */
export interface TimerGetWifiObservedResponse {
  "wifi"?: unknown;
  "wifi_func_2g"?: unknown;
  "wifi_func_5g"?: unknown;
}

/** Object keys observed for timer.get_screen on firmware 4.8.1. */
export interface TimerGetScreenObservedResponse {
  "turnon_hour"?: unknown;
  "turnoff_min"?: unknown;
  "turnon_min"?: unknown;
  "enable"?: unknown;
  "week"?: unknown;
  "turnoff_hour"?: unknown;
}

/** Object keys observed for plugins.get_config on firmware 4.8.1. */
export interface PluginsGetConfigObservedResponse {
  "source"?: unknown;
}

/** Object keys observed for plugins.get_repository_status on firmware 4.8.1. */
export interface PluginsGetRepositoryStatusObservedResponse {
  "time_current"?: unknown;
  "count_reserve"?: unknown;
  "count_updatable"?: unknown;
  "count_installed"?: unknown;
  "time_last_update"?: unknown;
  "count_all"?: unknown;
  "status"?: unknown;
  "count_not_installed"?: unknown;
}

/** Object keys observed for parental-control.get_config on firmware 4.8.1. */
export interface ParentalControlGetConfigObservedResponse {
  "enable_app"?: unknown;
  "groups"?: unknown;
  "enable"?: unknown;
  "drop_anonymous"?: unknown;
  "rules"?: unknown;
  "auto_update"?: unknown;
}

/** Object keys observed for parental-control.get_status on firmware 4.8.1. */
export interface ParentalControlGetStatusObservedResponse {
  "groups"?: unknown;
  "time_valid"?: unknown;
}

/** Object keys observed for parental-control.get_app_list on firmware 4.8.1. */
export interface ParentalControlGetAppListObservedResponse {
  "apps"?: unknown;
}

/** Object keys observed for black_white_list.get_config on firmware 4.8.1. */
export interface BlackWhiteListGetConfigObservedResponse {
  "mode"?: unknown;
}

/** Object keys observed for switch-button.get_config on firmware 4.8.1. */
export interface SwitchButtonGetConfigObservedResponse {
  "func"?: unknown;
  "sub_func"?: unknown;
}

/** Object keys observed for switch-button.get_funcs on firmware 4.8.1. */
export interface SwitchButtonGetFuncsObservedResponse {
  "funcs"?: unknown;
}

/** Object keys observed for local-access.get_config on firmware 4.8.1. */
export interface LocalAccessGetConfigObservedResponse {
  "session_timeout"?: unknown;
  "ssh_port"?: unknown;
  "https_port"?: unknown;
  "luci_redirect_https"?: unknown;
  "luci_http_port"?: unknown;
  "luci_https_port"?: unknown;
  "redirect_https"?: unknown;
  "ssh_enabled"?: unknown;
  "http_port"?: unknown;
}

/** Object keys observed for luci.get_status on firmware 4.8.1. */
export interface LuciGetStatusObservedResponse {
  "status"?: unknown;
}

/** Object keys observed for logread.get_module_name on firmware 4.8.1. */
export interface LogreadGetModuleNameObservedResponse {
  "modules"?: unknown;
}

/** Object keys observed for ui.get_menu_list on firmware 4.8.1. */
export interface UiGetMenuListObservedResponse {
  "menus"?: unknown;
}

/** Object keys observed for ipv6.get_ipv6 on firmware 4.8.1. */
export interface Ipv6GetIpv6ObservedResponse {
  "enable"?: unknown;
  "lan_dns_mode"?: unknown;
  "lan_mode"?: unknown;
}

/** Object keys observed for igmp.get_config on firmware 4.8.1. */
export interface IgmpGetConfigObservedResponse {
  "enable"?: unknown;
  "version"?: unknown;
}

/** Object keys observed for kmwan.get_config on firmware 4.8.1. */
export interface KmwanGetConfigObservedResponse {
  "interfaces"?: unknown;
  "mode"?: unknown;
}

/** Object keys observed for kmwan.get_status on firmware 4.8.1. */
export interface KmwanGetStatusObservedResponse {
  "interfaces"?: unknown;
}

/** Object keys observed for edgerouter.get_config on firmware 4.8.1. */
export interface EdgerouterGetConfigObservedResponse {
  "enable"?: unknown;
  "ignore"?: unknown;
}

/** Object keys observed for edgerouter.get_status on firmware 4.8.1. */
export interface EdgerouterGetStatusObservedResponse {
  "detected"?: unknown;
  "dns"?: unknown;
  "gateway"?: unknown;
  "valid"?: unknown;
  "netmask"?: unknown;
  "ip"?: unknown;
}

export interface SystemApi {
  getStatus(params?: RpcParams): Promise<SystemGetStatus>;
  getInfo(params?: RpcParams): Promise<SystemGetInfo>;
  getLoad(params?: RpcParams): Promise<SystemGetLoadObservedResponse>;
  getTimezoneConfig(params?: RpcParams): Promise<SystemGetTimezoneConfigObservedResponse>;
  getUsb3Disable(params?: RpcParams): Promise<SystemGetUsb3DisableObservedResponse>;
  setPassword(params: SetPasswordParams): Promise<unknown>;
  setTimezoneConfig(params?: RpcParams): Promise<unknown>;
  setUsb3Disable(params?: RpcParams): Promise<unknown>;
  reboot(params?: RpcParams): Promise<unknown>;
  resetFirmware(params?: RpcParams): Promise<unknown>;
}

export interface VpnClientApi {
  getStatus(params?: RpcParams): Promise<VpnClientGetStatusObservedResponse>;
  getAllConfigList(params?: RpcParams): Promise<VpnClientGetAllConfigListObservedResponse>;
  getTunnel(params?: RpcParams): Promise<VpnClientGetTunnelObservedResponse>;
  getConnectionMethods(params?: RpcParams): Promise<VpnClientGetConnectionMethodsObservedResponse>;
  getVpnUsingStatus(params?: RpcParams): Promise<unknown>;
  addTunnel(params: AddTunnelParams): Promise<unknown>;
  setTunnel(params: SetTunnelParams): Promise<unknown>;
  removeTunnel(params?: RpcParams): Promise<unknown>;
  setDefaultTunnel(params?: RpcParams): Promise<unknown>;
  setGlobalMode(params?: RpcParams): Promise<unknown>;
  setOptions(params: VpnOptionsParams): Promise<unknown>;
  setTapS2s(params?: RpcParams): Promise<unknown>;
  setSingleMac(params?: RpcParams): Promise<unknown>;
  startRandomClient(params?: RpcParams): Promise<unknown>;
  stop(params?: RpcParams): Promise<unknown>;
  orderTunnel(params?: RpcParams): Promise<unknown>;
  checkDomainOnline(params?: RpcParams): Promise<unknown>;
}

export interface WgClientApi {
  getGroupList(params?: RpcParams): Promise<WgClientGetGroupListObservedResponse>;
  getConfigList(params?: RpcParams): Promise<unknown>;
  addConfig(params: WgClientAddConfigParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  removeConfig(params?: RpcParams): Promise<unknown>;
  addGroup(params?: RpcParams): Promise<unknown>;
  setGroup(params?: RpcParams): Promise<unknown>;
  removeGroup(params?: RpcParams): Promise<unknown>;
  clearConfigList(params?: RpcParams): Promise<unknown>;
  clearUserPass(params?: RpcParams): Promise<unknown>;
  checkConfig(params?: RpcParams): Promise<unknown>;
  confirmConfig(params?: RpcParams): Promise<unknown>;
}

export interface WgClientProviderApi {
  genKey(params?: RpcParams): Promise<unknown>;
  getMaxClient(params?: RpcParams): Promise<unknown>;
  getProviderUserInfo(params?: RpcParams): Promise<unknown>;
  createProviderAccount(params?: RpcParams): Promise<unknown>;
  updateProviderConfig(params?: RpcParams): Promise<unknown>;
}

export interface WgServerApi {
  getConfig(params?: RpcParams): Promise<WgServerGetConfigObservedResponse>;
  getSetting(params?: RpcParams): Promise<WgServerGetSettingObservedResponse>;
  getPeerList(params?: RpcParams): Promise<WgServerGetPeerListObservedResponse>;
  setConfig(params: WgServerSetConfigParams): Promise<unknown>;
  setSetting(params: VpnOptionsParams): Promise<unknown>;
  addPeer(params: WgServerAddPeerParams): Promise<unknown>;
  setPeer(params?: RpcParams): Promise<unknown>;
  removePeer(params?: RpcParams): Promise<unknown>;
  generateKey(params?: RpcParams): Promise<unknown>;
  generatePeer(params?: RpcParams): Promise<unknown>;
  generatePublickey(params?: RpcParams): Promise<unknown>;
  start(params?: RpcParams): Promise<unknown>;
  stop(params?: RpcParams): Promise<unknown>;
}

export interface OvpnClientApi {
  getGroupList(params?: RpcParams): Promise<OvpnClientGetGroupListObservedResponse>;
  getConfigList(params?: RpcParams): Promise<unknown>;
  getRecommendConfig(params?: RpcParams): Promise<unknown>;
  getThirdConfig(params?: RpcParams): Promise<unknown>;
  addConfig(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  removeConfig(params?: RpcParams): Promise<unknown>;
  addGroup(params?: RpcParams): Promise<unknown>;
  setGroup(params?: RpcParams): Promise<unknown>;
  removeGroup(params?: RpcParams): Promise<unknown>;
  clearConfigList(params?: RpcParams): Promise<unknown>;
  clearUserPass(params?: RpcParams): Promise<unknown>;
  checkConfig(params?: RpcParams): Promise<unknown>;
  confirmConfig(params?: RpcParams): Promise<unknown>;
}

export interface OvpnClientLegacyApi {
  setConfigName(params?: RpcParams): Promise<unknown>;
}

export interface OvpnServerApi {
  getConfig(params?: RpcParams): Promise<OvpnServerGetConfigObservedResponse>;
  getSetting(params?: RpcParams): Promise<OvpnServerGetSettingObservedResponse>;
  getUserList(params?: RpcParams): Promise<OvpnServerGetUserListObservedResponse>;
  setConfig(params: OvpnServerSetConfigParams): Promise<unknown>;
  setSetting(params: VpnOptionsParams): Promise<unknown>;
  addUser(params?: RpcParams): Promise<unknown>;
  removeUser(params?: RpcParams): Promise<unknown>;
  exportConfig(params?: RpcParams): Promise<unknown>;
  generateCertificate(params?: RpcParams): Promise<unknown>;
}

export interface WifiApi {
  getStatus(params?: RpcParams): Promise<WifiGetStatus>;
  getConfig(params?: RpcParams): Promise<WifiGetConfigObservedResponse>;
  setConfig(params: SetWifiConfigParams): Promise<unknown>;
  setTxpower(params?: RpcParams): Promise<unknown>;
  getMloConfig(params?: RpcParams): Promise<unknown>;
  setMloConfig(params?: RpcParams): Promise<unknown>;
}

export interface ClientsApi {
  getStatus(params?: RpcParams): Promise<ClientsGetStatus>;
  getList(params?: RpcParams): Promise<ClientsGetListObservedResponse>;
  setInfo(params?: RpcParams): Promise<unknown>;
  removeOffline(params?: RpcParams): Promise<unknown>;
  cleanTraffic(params?: RpcParams): Promise<unknown>;
}

export interface FirewallApi {
  getPortForwardList(params?: RpcParams): Promise<FirewallGetPortForwardListObservedResponse>;
  getRuleList(params?: RpcParams): Promise<FirewallGetRuleListObservedResponse>;
  getZoneList(params?: RpcParams): Promise<FirewallGetZoneListObservedResponse>;
  getDmz(params?: RpcParams): Promise<FirewallGetDmzObservedResponse>;
  getWanAccess(params?: RpcParams): Promise<FirewallGetWanAccessObservedResponse>;
  addPortForward(params: AddPortForwardParams): Promise<unknown>;
  setPortForward(params?: RpcParams): Promise<unknown>;
  removePortForward(params?: RpcParams): Promise<unknown>;
  orderPortForward(params?: RpcParams): Promise<unknown>;
  addRule(params?: RpcParams): Promise<unknown>;
  setRule(params?: RpcParams): Promise<unknown>;
  removeRule(params?: RpcParams): Promise<unknown>;
  setDmz(params: SetDmzParams): Promise<unknown>;
  setWanAccess(params: SetWanAccessParams): Promise<unknown>;
}

export interface DnsApi {
  getConfig(params?: RpcParams): Promise<DnsGetConfig>;
  getInfo(params?: RpcParams): Promise<DnsGetInfoObservedResponse>;
  getHost(params?: RpcParams): Promise<unknown>;
  setConfig(params: SetDnsConfigParams): Promise<unknown>;
  setHost(params?: RpcParams): Promise<unknown>;
}

export interface LanApi {
  getConfigList(params?: RpcParams): Promise<LanGetConfigListObservedResponse>;
  getStaticBindList(params?: RpcParams): Promise<LanGetStaticBindListObservedResponse>;
  getWanInfo(params?: RpcParams): Promise<LanGetWanInfoObservedResponse>;
  setConfig(params: LanSetConfigParams): Promise<unknown>;
  addStaticBind(params: AddStaticBindParams): Promise<unknown>;
  setStaticBind(params?: RpcParams): Promise<unknown>;
  removeStaticBind(params?: RpcParams): Promise<unknown>;
}

export interface NetworkApi {
  getAdvanceConfig(params?: RpcParams): Promise<NetworkGetAdvanceConfigObservedResponse>;
  getNetnatConfig(params?: RpcParams): Promise<NetworkGetNetnatConfigObservedResponse>;
  getArpList(params?: RpcParams): Promise<NetworkGetArpListObservedResponse>;
  getAvailableAddressList(params?: RpcParams): Promise<unknown>;
  checkWanCable(params?: RpcParams): Promise<unknown>;
  setAdvanceConfig(params?: RpcParams): Promise<unknown>;
  setNetnatConfig(params?: RpcParams): Promise<unknown>;
}

export interface CableApi {
  getConfig(params?: RpcParams): Promise<CableGetConfigObservedResponse>;
  getPortsConfig(params?: RpcParams): Promise<CableGetPortsConfigObservedResponse>;
  getPortsStatus(params?: RpcParams): Promise<CableGetPortsStatusObservedResponse>;
  getStatus(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  setPortConfig(params?: RpcParams): Promise<unknown>;
  initStatus(params?: RpcParams): Promise<unknown>;
  wanProtoDetect(params?: RpcParams): Promise<unknown>;
}

export interface RepeaterApi {
  getStatus(params?: RpcParams): Promise<RepeaterGetStatus>;
  getConfig(params?: RpcParams): Promise<RepeaterGetConfig>;
  getSavedApList(params?: RpcParams): Promise<RepeaterGetSavedApListObservedResponse>;
  getChannelPrompt(params?: RpcParams): Promise<unknown>;
  scan(params?: RpcParams): Promise<unknown>;
  connect(params: RepeaterConnectParams): Promise<unknown>;
  disconnect(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  removeSavedAp(params?: RpcParams): Promise<unknown>;
  setChannelPrompt(params?: RpcParams): Promise<unknown>;
  enterBareMode(params?: RpcParams): Promise<unknown>;
  exitBareMode(params?: RpcParams): Promise<unknown>;
}

export interface TetheringApi {
  getConfig(params?: RpcParams): Promise<unknown>;
  getStatus(params?: RpcParams): Promise<TetheringGetStatusObservedResponse>;
  setConnect(params?: RpcParams): Promise<unknown>;
  disconnect(params?: RpcParams): Promise<unknown>;
}

export interface NetmodeApi {
  getMode(params?: RpcParams): Promise<NetmodeGetModeObservedResponse>;
  setMode(params?: RpcParams): Promise<unknown>;
}

export interface TailscaleApi {
  getStatus(params?: RpcParams): Promise<TailscaleGetStatus>;
  getConfig(params?: RpcParams): Promise<TailscaleGetConfig>;
  getExitNodeList(params?: RpcParams): Promise<unknown>;
  getAuthUrl(params?: RpcParams): Promise<unknown>;
  setConfig(params: TailscaleSetConfigParams): Promise<unknown>;
  logout(params?: RpcParams): Promise<unknown>;
}

export interface ZerotierApi {
  getStatus(params?: RpcParams): Promise<unknown>;
  getConfig(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface TorApi {
  getStatus(params?: RpcParams): Promise<unknown>;
  getConfig(params?: RpcParams): Promise<TorGetConfig>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface AdguardhomeApi {
  getConfig(params?: RpcParams): Promise<AdGuardHomeGetConfig>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface DdnsApi {
  getStatus(params?: RpcParams): Promise<DdnsGetStatus>;
  getConfig(params?: RpcParams): Promise<DdnsGetConfig>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface CloudApi {
  getConfig(params?: RpcParams): Promise<CloudGetConfig>;
  setConfig(params?: RpcParams): Promise<unknown>;
  unbind(params?: RpcParams): Promise<unknown>;
}

export interface LedApi {
  getConfig(params?: RpcParams): Promise<LedGetConfig>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface FanApi {
  getStatus(params?: RpcParams): Promise<FanGetStatus>;
  getConfig(params?: RpcParams): Promise<FanGetConfig>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface TimerApi {
  getLed(params?: RpcParams): Promise<TimerGetLedObservedResponse>;
  getReboot(params?: RpcParams): Promise<TimerGetRebootObservedResponse>;
  getWifi(params?: RpcParams): Promise<TimerGetWifiObservedResponse>;
  getScreen(params?: RpcParams): Promise<TimerGetScreenObservedResponse>;
  setLed(params: TimerSetParams): Promise<unknown>;
  setReboot(params?: RpcParams): Promise<unknown>;
  setWifi(params?: RpcParams): Promise<unknown>;
  setScreen(params?: RpcParams): Promise<unknown>;
}

export interface PluginsApi {
  getConfig(params?: RpcParams): Promise<PluginsGetConfigObservedResponse>;
  getList(params?: RpcParams): Promise<unknown>;
  getRepositoryStatus(params?: RpcParams): Promise<PluginsGetRepositoryStatusObservedResponse>;
  getPackageInfo(params?: RpcParams): Promise<unknown>;
  installPackage(params: PluginsInstallParams): Promise<unknown>;
  removePackage(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  updateRepository(params?: RpcParams): Promise<unknown>;
}

export interface ParentalControlApi {
  getConfig(params?: RpcParams): Promise<ParentalControlGetConfigObservedResponse>;
  getStatus(params?: RpcParams): Promise<ParentalControlGetStatusObservedResponse>;
  getMode(params?: RpcParams): Promise<unknown>;
  getAppList(params?: RpcParams): Promise<ParentalControlGetAppListObservedResponse>;
  getBrief(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  setMode(params?: RpcParams): Promise<unknown>;
  setBrief(params?: RpcParams): Promise<unknown>;
  addGroup(params?: RpcParams): Promise<unknown>;
  setGroup(params?: RpcParams): Promise<unknown>;
  removeGroup(params?: RpcParams): Promise<unknown>;
  addRule(params?: RpcParams): Promise<unknown>;
  setRule(params?: RpcParams): Promise<unknown>;
  removeRule(params?: RpcParams): Promise<unknown>;
  checkBlacklistOnline(params?: RpcParams): Promise<unknown>;
}

export interface QosApi {
  getConfig(params?: RpcParams): Promise<unknown>;
  setSpeedLimitRule(params: SetSpeedLimitRuleParams): Promise<unknown>;
  removeSpeedLimitRule(params?: RpcParams): Promise<unknown>;
}

export interface BlackWhiteListApi {
  getConfig(params?: RpcParams): Promise<BlackWhiteListGetConfigObservedResponse>;
  setConfig(params?: RpcParams): Promise<unknown>;
  setSingleMac(params?: RpcParams): Promise<unknown>;
}

export interface SwitchButtonApi {
  getConfig(params?: RpcParams): Promise<SwitchButtonGetConfigObservedResponse>;
  getFuncs(params?: RpcParams): Promise<SwitchButtonGetFuncsObservedResponse>;
  setConfig(params?: RpcParams): Promise<unknown>;
  checkSyncStatus(params?: RpcParams): Promise<unknown>;
}

export interface LocalAccessApi {
  getConfig(params?: RpcParams): Promise<LocalAccessGetConfigObservedResponse>;
  setConfig(params: LocalAccessSetConfigParams): Promise<unknown>;
}

export interface LuciApi {
  getStatus(params?: RpcParams): Promise<LuciGetStatusObservedResponse>;
  installLuci(params?: RpcParams): Promise<unknown>;
  uninstallLuci(params?: RpcParams): Promise<unknown>;
}

export interface LogreadApi {
  getSystemLog(params?: RpcParams): Promise<unknown>;
  getKernelLog(params?: RpcParams): Promise<unknown>;
  getCrashLog(params?: RpcParams): Promise<unknown>;
  getNginxLog(params?: RpcParams): Promise<unknown>;
  getEsimLog(params?: RpcParams): Promise<unknown>;
  getModuleName(params?: RpcParams): Promise<LogreadGetModuleNameObservedResponse>;
  getConfig(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  exportLogs(params?: RpcParams): Promise<unknown>;
  removeCrashLog(params?: RpcParams): Promise<unknown>;
}

export interface UpgradeApi {
  getConfig(params?: RpcParams): Promise<UpgradeGetConfig>;
  setConfig(params?: RpcParams): Promise<unknown>;
  checkFirmwareOnline(params?: RpcParams): Promise<unknown>;
  checkFirmwareLocal(params?: RpcParams): Promise<unknown>;
  checkCellularOnline(params?: RpcParams): Promise<unknown>;
  checkCellularLocal(params?: RpcParams): Promise<unknown>;
  getOnlineUpgradeStatus(params?: RpcParams): Promise<unknown>;
  getCellularUpgradeStatus(params?: RpcParams): Promise<unknown>;
  resetCellularUpgradeStatus(params?: RpcParams): Promise<unknown>;
  upgradeOnline(params?: RpcParams): Promise<unknown>;
  upgradeLocal(params?: RpcParams): Promise<unknown>;
}

export interface UiApi {
  getMenuList(params?: RpcParams): Promise<UiGetMenuListObservedResponse>;
  getRemoteLangs(params?: RpcParams): Promise<unknown>;
  setLang(params?: RpcParams): Promise<unknown>;
  setInitedInternet(params?: RpcParams): Promise<unknown>;
  updateLangs(params?: RpcParams): Promise<unknown>;
}

export interface Ipv6Api {
  getIpv6(params?: RpcParams): Promise<Ipv6GetIpv6ObservedResponse>;
  setIpv6(params?: RpcParams): Promise<unknown>;
}

export interface IgmpApi {
  getConfig(params?: RpcParams): Promise<IgmpGetConfigObservedResponse>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface KmwanApi {
  getConfig(params?: RpcParams): Promise<KmwanGetConfigObservedResponse>;
  getStatus(params?: RpcParams): Promise<KmwanGetStatusObservedResponse>;
  getSensitivity(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  setInterface(params?: RpcParams): Promise<unknown>;
  setSensitivity(params?: RpcParams): Promise<unknown>;
}

export interface EdgerouterApi {
  getConfig(params?: RpcParams): Promise<EdgerouterGetConfigObservedResponse>;
  getStatus(params?: RpcParams): Promise<EdgerouterGetStatusObservedResponse>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface RttyApi {
  getConfig(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface SmsForwardApi {
  getConfig(params?: RpcParams): Promise<unknown>;
  setEmail(params?: RpcParams): Promise<unknown>;
  setPhoneNumber(params?: RpcParams): Promise<unknown>;
}

export interface ModemApi {
  getInfo(params?: RpcParams): Promise<unknown>;
  getStatus(params?: RpcParams): Promise<unknown>;
  getSimConfig(params?: RpcParams): Promise<unknown>;
  getSlotConfig(params?: RpcParams): Promise<unknown>;
  getCellsInfo(params?: RpcParams): Promise<unknown>;
  getCellTower(params?: RpcParams): Promise<unknown>;
  getTrafficConfig(params?: RpcParams): Promise<unknown>;
  getOperatorConfig(params?: RpcParams): Promise<unknown>;
  getDebugMsg(params?: RpcParams): Promise<unknown>;
  getProfileList(params?: RpcParams): Promise<unknown>;
  getApnPollEnabled(params?: RpcParams): Promise<unknown>;
  getSimcardInfo(params?: RpcParams): Promise<unknown>;
  getSmsList(params?: RpcParams): Promise<unknown>;
  setSimConfig(params?: RpcParams): Promise<unknown>;
  setSlotConfig(params?: RpcParams): Promise<unknown>;
  setConnect(params?: RpcParams): Promise<unknown>;
  disconnect(params?: RpcParams): Promise<unknown>;
  setSimPinCode(params?: RpcParams): Promise<unknown>;
  setCellTower(params?: RpcParams): Promise<unknown>;
  scanCellTower(params?: RpcParams): Promise<unknown>;
  scanOperatorList(params?: RpcParams): Promise<unknown>;
  setOperatorConfig(params?: RpcParams): Promise<unknown>;
  setApnPollEnabled(params?: RpcParams): Promise<unknown>;
  setTrafficConfig(params?: RpcParams): Promise<unknown>;
  rebootModem(params?: RpcParams): Promise<unknown>;
  sendAtCommand(params?: RpcParams): Promise<unknown>;
  sendSms(params?: RpcParams): Promise<unknown>;
  setSms(params?: RpcParams): Promise<unknown>;
  removeSms(params?: RpcParams): Promise<unknown>;
}

export interface MptunApi {
  getConfig(params?: RpcParams): Promise<unknown>;
  getToken(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface BarkApi {
  getConfig(params?: RpcParams): Promise<unknown>;
  getStatus(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
  logout(params?: RpcParams): Promise<unknown>;
}

export interface MvasApi {
  getConnectInfo(params?: RpcParams): Promise<unknown>;
  setConnectSlotNet(params?: RpcParams): Promise<unknown>;
  disconnectSlotNet(params?: RpcParams): Promise<unknown>;
  switchSimSlot(params?: RpcParams): Promise<unknown>;
}

export interface SqmApi {
  getConfig(params?: RpcParams): Promise<unknown>;
  setConfig(params?: RpcParams): Promise<unknown>;
}

export interface DpiApi {
  getQos(params?: RpcParams): Promise<unknown>;
  getApps(params?: RpcParams): Promise<unknown>;
  getContentProtection(params?: RpcParams): Promise<unknown>;
  getDpiStatus(params?: RpcParams): Promise<unknown>;
  getDpiConfig(params?: RpcParams): Promise<unknown>;
  checkDpiUpgrade(params?: RpcParams): Promise<unknown>;
  checkLibUpgrade(params?: RpcParams): Promise<unknown>;
  getSubscribePopup(params?: RpcParams): Promise<unknown>;
  getDpiStats(params?: RpcParams): Promise<unknown>;
  setQos(params?: RpcParams): Promise<unknown>;
  setContentProtection(params?: RpcParams): Promise<unknown>;
  modAppContentProtection(params?: RpcParams): Promise<unknown>;
  setDpiConfig(params?: RpcParams): Promise<unknown>;
  setDpiUpgrade(params?: RpcParams): Promise<unknown>;
  setLibUpgrade(params?: RpcParams): Promise<unknown>;
  enableDpiBaseService(params?: RpcParams): Promise<unknown>;
  setIgnoreSubuscribe(params?: RpcParams): Promise<unknown>;
  setDpiBaseServiceConfirm(params?: RpcParams): Promise<unknown>;
}

export interface GlSdk4Api {
  system: SystemApi;
  vpnClient: VpnClientApi;
  wgClient: WgClientApi;
  wgClientProvider: WgClientProviderApi;
  wgServer: WgServerApi;
  ovpnClient: OvpnClientApi;
  ovpnClientLegacy: OvpnClientLegacyApi;
  ovpnServer: OvpnServerApi;
  wifi: WifiApi;
  clients: ClientsApi;
  firewall: FirewallApi;
  dns: DnsApi;
  lan: LanApi;
  network: NetworkApi;
  cable: CableApi;
  repeater: RepeaterApi;
  tethering: TetheringApi;
  netmode: NetmodeApi;
  tailscale: TailscaleApi;
  zerotier: ZerotierApi;
  tor: TorApi;
  adguardhome: AdguardhomeApi;
  ddns: DdnsApi;
  cloud: CloudApi;
  led: LedApi;
  fan: FanApi;
  timer: TimerApi;
  plugins: PluginsApi;
  parentalControl: ParentalControlApi;
  qos: QosApi;
  blackWhiteList: BlackWhiteListApi;
  switchButton: SwitchButtonApi;
  localAccess: LocalAccessApi;
  luci: LuciApi;
  logread: LogreadApi;
  upgrade: UpgradeApi;
  ui: UiApi;
  ipv6: Ipv6Api;
  igmp: IgmpApi;
  kmwan: KmwanApi;
  edgerouter: EdgerouterApi;
  rtty: RttyApi;
  smsForward: SmsForwardApi;
  modem: ModemApi;
  mptun: MptunApi;
  bark: BarkApi;
  mvas: MvasApi;
  sqm: SqmApi;
  dpi: DpiApi;
}
